return {
  {
    "nvim-treesitter/nvim-treesitter",
    event = { "VeryLazy", "BufEnter" },
    opts = {
      ensure_installed = {
        "lua",
        "vim",
        "vimdoc",
        "python",
        "requirements",
        "cpp",
        "javascript",
        "typescript",
        "tsx",
        "html",
        "yaml",
        "toml",
        "markdown",
        "gitignore",
        "gitcommit",
        "git_config",
        "gitattributes",
        "git_rebase",
        "ini",
        "json",
        "regex",
      },
    },
  },
}
